[tools]
"github:pnpm/pnpm" = "v11.5.0"
"rust" = { version = "1.95.0", profile = "default" }

[hooks]
postinstall = "pnpm install"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
